language: c

dist: trusty

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update || true
  - sudo apt-get install -qq gcc-5
  - sudo apt-get install -qq libncursesw5-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-5 20
  - sudo apt-get install -qq valgrind
script: make run-test-valgrind
