language: c

before_install:
  - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
  - sudo apt-get update || true
  - sudo apt-get install -qq gcc-5
  - sudo apt-get install -qq libncursesw5-dev
install: make dependency-update
script: make test-valgrind
