#ifndef ROGUE_CRAFT_DEFAULT_KEYMAP_H
#define ROGUE_CRAFT_DEFAULT_KEYMAP_H


#define KEY_NORTH       'w'
#define KEY_EAST        'd'
#define KEY_SOUTH       's'
#define KEY_WEST        'a'
#define KEY_QUIT       KEY_F(2)
#define KEY_PLAYER_INVENTORY   'i'
#define KEY_USE_SELECTED         'e'
#define KEY_INVENTORY_SHORTCUT_FIRST '1'
#define KEY_INVENTORY_SHORTCUTS \
    KEY_INVENTORY_SHORTCUT_FIRST, KEY_INVENTORY_SHORTCUT_FIRST + 1, KEY_INVENTORY_SHORTCUT_FIRST + 2, \
    KEY_INVENTORY_SHORTCUT_FIRST + 3, KEY_INVENTORY_SHORTCUT_FIRST + 4
#define KEY_DROP_ITEM        'q'
#define KEY_CRAFT       'c'


#endif
